services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./data/backend:/app/knowledgebase
    ports:
      - "8083:8083"

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
